version: '3.7'

services:

  nginx:
    image: "csatlos/grocy-nginx:v2.7.1-3"
    build:
      args:
        GROCY_VERSION: v2.7.1
      context: .
      dockerfile: Dockerfile-grocy-nginx
    depends_on:
      - grocy
    ports:
      - '9180:8080'
      - '9143:8443'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/nginx
    container_name: grocy-nginx
    networks:
      - net_homeapps
    secrets:
      - source: grocy_ssl_cert
        uid: '101'
        gid: '101'
        mode: 0440
      - source: grocy_ssl_key
        uid: '101'
        gid: '101'
        mode: 0440
  grocy:
    image: "csatlos/grocy:v2.7.1-3"
    build:
      args:
        GITHUB_API_TOKEN: "${GITHUB_API_TOKEN}"
        GROCY_VERSION: v2.7.1
      context: .
      dockerfile: Dockerfile-grocy
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/php7
      - app-db:/var/www/data
    env_file:
      - grocy.env
    container_name: grocy
    networks:
      - net_homeapps

volumes:
  app-db:

networks:
  net_homeapps:
    external: true
    name: net_homeapps

secrets:
  grocy_ssl_cert:
    file: /root/certs/grocy/grocy.lan.clc.pw.crt
  grocy_ssl_key:
    file: /root/certs/grocy/grocy.lan.clc.pw.key

