version: '3.7'

services:

  nginx:
    image: "grocy/nginx:v2.7.1-3"
    build:
      args:
        GROCY_VERSION: v2.7.1
      context: .
      dockerfile: Dockerfile-grocy-nginx
    depends_on:
      - grocy
    ports:
      - '127.0.0.1:80:8080'
      - '127.0.0.1:443:8443'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/nginx
    container_name: nginx

  grocy:
    image: "grocy/grocy:v2.7.1-3"
    build:
      args:
        GITHUB_API_TOKEN: "${GITHUB_API_TOKEN}"
        GROCY_VERSION: v2.7.1
      context: .
      dockerfile: Dockerfile-grocy
    expose:
      - '9000'
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/php7
      - app-db:/var/www/data
    env_file:
      - grocy.env
    container_name: grocy

volumes:
  app-db:
